name: CICD

on:
  push:

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: write
    name: build-and-push
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout scm'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker build and push
      uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v1
      with:
        file: Dockerfile
        build-args: "DEPLOY_ENV=stg"
        tag: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/zilliqa-isolated-server-faucet
        tag-length: 7
        push: ${{ github.ref_name == github.event.repository.default_branch }}
        tag-latest: ${{ github.ref_name == github.event.repository.default_branch }}
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ECR_DEPLOYER_ROLE }}
        oidc-role: ${{ secrets.OIDC_ROLE }}
        cache-key: 'zilliqa-isolated-server-faucet'
