name: CICD

on:
  push:

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: write
    name: build-and-push
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout scm'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure AWS Credentials
      uses: Zilliqa/gh-actions-workflows/actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ECR_DEPLOYER_ROLE }}
        oidc-role: ${{ secrets.OIDC_ROLE }}
    - name: Split image and tag
      env:
        TRAVIS_COMMIT: ${{ github.sha }}
      run: |
        ./scripts/ci_build.sh
      shell: bash
    - name: Split image and tag
      if: ${{ github.ref_name == github.event.repository.default_branch }}
      run: |
        IFS=':'
        read -ra ADDR <<< "${{ inputs.tag }}"
        echo "image=${ADDR[0]}" >> $GITHUB_OUTPUT
        echo "tag=${ADDR[1]}" >> $GITHUB_OUTPUT
      shell: bash
